- name: shell vs command
  hosts: web
  become: yes
  tasks:
    - name: shell example
      ansible.builtin.shell: "echo 'hello world'"
    - name: shell example with multiple commands
      ansible.builtin.shell: ls -l > /tmp/ls_output.txt
      registers: output_testing
    - name: debug output
      ansible.builtin.debug:
        msg: "{{ output_testing }}"
    - name: command example
      ansible.builtin.command: "echo 'hello world'"