- name: mysql
  hosts: mysql
  become: yes
  tasks:
    - name: install mysql
      ansible.builtin.yum:
        name: mysql-server
        state: present
    - name: start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    
    - name: set root password
      community.mysql.mysql_user:
        login_user: root
        name: root
        login_password: "{{ mysql_root_password }}"
        host_all: yes
      register: mysql_root_user
